### ISSUE TITLE
Sublime Text 3

### ISSUE THREAD

**Issue by Militis** [francodacosta/composer-sublime#3]
Do you have any plans on adding Sublime Text 3 compatibility?

**Comment by francodacosta** [comment]
Yes I do,

I'm going to start porting my plugins to ST3 next week

**Comment by Militis** [comment]
Awesome, thanks!

**Comment by nifr** [comment]
any updates on ST3 compatibility for this plugin?

**Comment by chadrien** [comment]
Hi, I've started working on a [ST3 port of this package](https://github.com/chadrien/composer-sublime), but it seems there is huge work to be done (starting by refactoring, 503 lines files with many classes in it is barely readable) due to python3 depracation and new API from ST3.

Any help is welcome as it will be a lot of work to be done :)

I'll keep you up to date.

**Comment by francodacosta** [comment]
@chadrien @nifr  @Militis 

the new version should work with ST3 can you guys test it ?

cheers

**Comment by chadrien** [comment]
Yep looks like it works

**Comment by francodacosta** [comment]
@chadrien thanks
